language: php

php:
  - 7.2

services:
  - postgresql

env:
  - DB=mysql

install:
  - composer selfupdate
  - composer install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test_database;" -uroot; fi
  - psql -c 'create database test_database;' -U postgres

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls